name: Hotelaria CI (Gestão de Reservas)
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Simulação de Build
        run: echo "Compilando módulo de Reservas... OK"
      - name: Testes Automatizados
        run: echo "Verificando disponibilidade de quartos... SUCESSO"
